### ISSUE TITLE
demo not yet working?

### ISSUE THREAD

**Issue by staffhorn** [alexhallam/TensorFlow-Survival-Analysis#1]
It appears the demo notebook is not yet working.  @alexhallam are you still working on this?

**Comment by alexhallam** [comment]
Maybe if you post your error I can help out. One thing to note is that the code is in Python 2.

**Comment by alexhallam** [comment]
Maybe you are referring to 

`ImportError: bad magic number in 'deepsurv_tf': b'\x03\xf3\r\n'`

On my last commit I created this `deepsurv_tf.pyc` which is [known](https://stackoverflow.com/questions/514371/whats-the-bad-magic-number-error) to cause the magic number error. I will clean that up tonight and push.

**Comment by alexhallam** [comment]
I just reverted to an old commit that had a working [demo](https://github.com/alexhallam/TensorFlow-Survival-Analysis/blob/master/demo.ipynb). I also created a `req.txt` file if you run into any dependency issues.

**Comment by staffhorn** [comment]
Thanks, I'll try.

On Jun 2, 2017 10:28 AM, "Alex Hallam" <notifications@github.com> wrote:

I just reverted to an old commit that had a working demo
<https://github.com/alexhallam/TensorFlow-Survival-Analysis/blob/master/demo.ipynb>.
I also created a req.txt file if you run into any dependency issues.


.

**Comment by staffhorn** [comment]
Still getting this in the demo:

``
NameErrorTraceback (most recent call last)
<ipython-input-4-c78598a857c7> in <module>()
      1 params = deepsurv_tf.Parameters()
----> 2 params.n_in = train['x'].shape[1]
      3 params.n_epochs = epochs
      4 
      5 ds_tf = deepsurv_tf.DeepSurvTF(params)

NameError: name 'train' is not defined
``

**Comment by staffhorn** [comment]
I was able to sort out the dependencies and get the demo (reverted version) to work. Thanks.

**Comment by alexhallam** [comment]
You will notice that the hyperperameter search is tough. Jared is currently working on an Optunity script. The hope is that the scripts will improve the neural network. [See here](https://github.com/jaredleekatzman/DeepSurv/issues/3)

**Comment by staffhorn** [comment]
confirmed
