### ISSUE TITLE
true.csv not found

### ISSUE THREAD

**Issue by tiwaript** [alexhallam/TensorFlow-Survival-Analysis#5]
true.csv in survival.py was not found. any lead?

**Comment by alexhallam** [comment]
That is user supplied. If you do not have your own data then you should simulate data with `datasets.py`. 

https://github.com/alexhallam/TensorFlow-Survival-Analysis/blob/b1b07eacdc7349e99a8457dde54bc545e5c5a360/datasets.py#L158

Then pull the simulated data with the following lines.
 https://github.com/alexhallam/TensorFlow-Survival-Analysis/blob/b1b07eacdc7349e99a8457dde54bc545e5c5a360/Survival.py#L5-L6

The repo also comes with a `simulated_dat.csv`
